# device_id: <tofill>
# access_token: <tofill>
mxid: '@goodboy:matrix.org'
homeserver: https://matrix-client.matrix.org/
room_cache_size: 32
room_cache_age: 60
notify_sound: true
send_to_verified_only: false
backspace1_removes_word: true
backspace2_removes_word: false
always_clear_screen: true

# host specific dirs
# data_dir: /home/goodboy/.local/share/gomuks
# cache_dir: /home/goodboy/.cache/gomuks
# history_path: /home/goodboy/.cache/gomuks/history.db
# room_list_path: /home/goodboy/.cache/gomuks/rooms.gob.gz
# media_dir: /home/goodboy/.cache/gomuks/media
# download_dir: /home/goodboy/Downloads
# state_dir: /home/goodboy/.cache/gomuks/state
