#
# Tyler Goodlet .zshrc config file
#

# history
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
HISTIGNORE=' '
setopt appendhistory
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history

# completion
zstyle :compinstall filename '$HOME/.zshrc'
autoload -Uz compinit && compinit

# changing directories
#setopt autocd
setopt autopushd
setopt cdable_vars
setopt chase_links
setopt pushd_ignore_dups

# fxpansion and globbing
setopt extendedglob
setopt nomatch
setopt notify

# zle
unsetopt beep
bindkey -v      # vi front end

# zprofile
export TERM=screen-256color
export PATH="${PATH}:${HOME}/etc/bin:${HOME}/.cabal/bin"
# export PYTHONPATH="/usr/lib/python3.3/site-packages/"

# {{{1 Bindkeys
# bindkey "^[[A" history-beginning-search-backward
# bindkey "^[[B" history-beginning-search-forward
# bindkey "\e[1~" beginning-of-line
# bindkey "\e[4~" end-of-line
# bindkey "\e[7~" beginning-of-line
# bindkey "\e[8~" end-of-line
# bindkey "\e[5~" beginning-of-history
# bindkey "\e[6~" end-of-history
# bindkey "\e[3~" delete-char
# bindkey "\e[2~" quoted-insert
# bindkey "\e\e[C" forward-word
# bindkey "\e\e[D" backward-word
# bindkey "\e[5C" forward-word
# bindkey "\e[5D" backward-word
# bindkey "\eOc" emacs-forward-word
# bindkey "\eOd" emacs-backward-word
#bindkey "^H" backward-delete-word
bindkey '^R' history-incremental-search-backward

# CTRL-Q for vi normal mode
bindkey '^q' vicmd

# completion in the middle of a line
bindkey '^i' expand-or-complete-prefix

# buffer stack access
bindkey '^w' push-line
bindkey '^e' get-line
#}}}

# Display settings
# If not running interactively, don't do this
[[ $- != *i* ]] && return

# load snippets
for snippets (${HOME}/.zsh_snippets/*.zsh(N))
      source $snippets
