theme = "rasmus"
# theme = "everblush"

# ------ - ------

[editor]
true-color = true
color-modes = true
# mouse = false

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator"]
center = ["spinner"]
right = [
  "file-line-ending",
  "separator",
  "position",
  "separator",
  "spacer",
  "position-percentage",
]
separator = "│"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
# to that you can see wtf the implied selection is XD
normal = "underline"
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

# ------ - ------

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-c = ["collapse_selection", "normal_mode"]

# config
# C-o = ":config-open"
C-r = ":config-reload"

# vim-like-remaps
# ----- - ------
# hard mode cancel
#C-c = ['normal_mode', 'collapse_selection']  # ctl-c always is cancel to normal

# yank and put
x = "delete_selection"
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]

0 = 'goto_line_start'
'$' = 'goto_line_end'
#G = 'goto_l":config-open"ast_line'
G = "goto_file_end"

# Undoing the 'd' + motion commands restores the selection which is annoying
u = ["undo", "collapse_selection"]

# search by hotkey
# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

# window nav
C-l = 'jump_view_right'
C-k = 'jump_view_up'
# C-k = 'jump_view_up'
# C-k = 'jump_view_up'

# defs nav
# 'C-]' = 'goto_definition'  # doesn't work?
#"{" = ["goto_prev_paragraph", "collapse_selection"]
#"}" = ["goto_next_paragraph", "collapse_selection"]
# this makes w and b behave as they do Vim
w = ["move_next_word_start", "move_char_right", "collapse_selection"]

# editz
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]


[keys.insert]
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
C-c = ["collapse_selection", "normal_mode"]

#g = { a = "code_action" } # Maps `ga` to show possible code actions
#"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
#j = { k = "normal_mode" } # Maps `jk` to exit insert mode

# Extend and select commands that expect a manual input can't be chained
# I've kept d[X] commands here because it's better to at least have the stuff you want to delete
# selected so that it's just a keystroke away to delete
[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
# w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]

[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]

[keys.normal.g]
# like C-i/o xcept stick with the whole 'g for go' type thing
i = 'jump_forward'
o = 'jump_backward'
# comment toggle then move to normal mode
c = [
  "select_mode",
  "extend_to_line_bounds",
  'toggle_comments',
  'normal_mode'
]
j = 'goto_definition'
'/' = 'goto_reference'
k = 'goto_reference'
']' = 'goto_reference'
#[keys.normal.{]
#{ = 'goto_prev_function'

#[keys.normal.{]
#k = 'goto_prev_function'

# .. can't get these to work..
# '[[' = 'goto_prev_class'
# ']]' = 'goto_next_class'


[keys.select]
C-c = ["collapse_selection", "keep_primary_selection", "normal_mode"]

"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
# "^" = "goto_first_nonwhitespace"  # never used it..
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
#"%" = "match_brackets"  # use helix's `mm`instead B)
S = "surround_add" # Basically 99% of what I use vim-surround for
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

# Make selecting lines in visual mode behave sensibly
# k = ["extend_line_up", "extend_to_line_bounds"]
# j = ["extend_line_down", "extend_to_line_bounds"]

# Clipboards over registers ye ye
d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
p = "replace_selections_with_clipboard" # No life without this
P = "paste_clipboard_before"

[keys.select.g]
c = ['toggle_comments', 'normal_mode']
