#!/bin/bash
#
# Executed by startx (run your window manager from here)

# activate custom kbd mapping
setxkbmap -option caps:ctrl_modifier

# set and alt-shell for the desktop env
_shell="zsh"
_xonsh="$(which $_shell)"
export SHELL="${_xonsh:-SHELL}"
# use neovim system wide
export EDITOR="nvim"

# ib-tws hack for i3
export _JAVA_AWT_WM_NONREPARENTING=1

# launch with wm of choice
cd
case "$2" in
    gnome)
        exec gnome-session;;
    *)
        systemctl --user import-environment DISPLAY XAUTHORITY
        dcus-update-activation-environment --all
        exec ${2:-i3};;
esac
