#!/bin/bash
#
# Executed by startx (run your window manager from here)

# activate custom kbd mappings
if [ -s ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi

# launch with wm of choice
cd
case "$2" in
    gnome)
        exec gnome-session;;
    *)
        systemctl --user import-environment DISPLAY XAUTHORITY
        dbus-update-activation-environment --all
        exec ${2:-i3};;
esac
